
openapi: 3.0.3
info:
  title: Arduino LED API
  description: A REST API to control and monitor LED states on an Arduino Nano via USB.
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /setLedStatus:
    post:
      summary: Set the LED states on the Arduino
      operationId: setLedStatus
      requestBody:
        description: |
          LED control command supporting three formats:
          Parse LED command in format: SSSS:OOOO:III or simple SSSS
          **Format 1 - Simple (Backward compatible with previous version):**
          - SSSS (4 digits: 0=off, 1=on)
          - Example: "1010" - Red ON, Yellow OFF, Green ON, Blue OFF
          
          **Format 2 - Turn on, off or blink with Sequence and Interval:**
          - SSSS:OOOO:III
          - SSSS = LED states (0=off, 1=on steady, 2=blink)
          - OOOO = Blink sequence order (0=no sequence, 1-4=position)
          - III = Blink interval in milliseconds (100-5000, default 500)
          
          **Usage Examples:**
          - "1010" - LEDs 1,3 steady on
          - "2020:0000:1000" - LEDs 1,3 blink together at 1000ms
          - "2222:1234:250" - All LEDs blink in sequence at 250ms
          - "1210:0021:500" - LED1 steady, LED2 blinks, LED4 blinks (seq order 2,1)
          - "STATUS" - Query current LED states (use GET /status instead)
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pattern:
                  type: string
                  example: "1010"
                  description: "LED control command: simple '1010' or extended 'SSSS:OOOO:III' format"
      responses:
        '200':
          description: LED pattern sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Sent simple pattern '1010' to Arduino"
                  command:
                    type: string
                    example: "1010"
                  details:
                    type: object
                    description: "For extended format commands only"
                    properties:
                      states:
                        type: string
                      sequence_order:
                        type: string
                      interval_ms:
                        type: integer
        '400':
          description: Invalid pattern format or invalid command
        '500':
          description: Arduino not connected or communication error

  /status:
    get:
      summary: Get the current status of all LEDs
      operationId: getStatus
      responses:
        '200':
          description: Successfully retrieved status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "connected"
                  port:
                    type: string
                    example: "COM3"
                  arduino_reply:
                    type: string
                    example: "redPin:12=1 yellowPin:11=0 greenPin:10=1 bluePin:9=0"
        '404':
          description: Arduino not found
        '500':
          description: Serial port error
